/*
 * narbis_protocol.h — shared protocol definitions for the Narbis earclip.
 *
 * This file is the SINGLE SOURCE OF TRUTH for:
 *   - ESP-NOW packet layout (wire format) between the earclip and Edge glasses.
 *   - BLE service / characteristic UUIDs exposed by the earclip.
 *   - The runtime-tweakable configuration struct.
 *   - Internal types shared across firmware components (e.g. beat_event_t).
 *
 * Conventions (DO NOT VIOLATE — see CLAUDE.md):
 *   - All multi-byte integers are little-endian on the wire.
 *   - All wire structs use __attribute__((packed)).
 *   - No `bool` (use uint8_t with 0/1).
 *   - No bit fields anywhere — use bitmask macros over uint8_t / uint16_t.
 *   - No floating point in wire formats — use fixed-point ints (e.g. _x10, _x100).
 *   - No encryption/signing fields (deferred to v2).
 *   - The TypeScript mirror is protocol/narbis_protocol.ts; protocol/check_sync.py
 *     verifies the two stay in sync.
 */

#ifndef NARBIS_PROTOCOL_H
#define NARBIS_PROTOCOL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* =============================================================
 * Protocol version
 * ============================================================= */

#define NARBIS_PROTOCOL_VERSION 1

/* =============================================================
 * BLE UUIDs (generated by protocol/generate_uuids.py)
 *
 * The _STR form is used by ble_gatts setup paths that take strings.
 * The _BYTES form is the little-endian byte order required by ESP-IDF's
 * esp_bt_uuid_t / ble_uuid128_t fields.
 *
 * Standard SIG services (used as-is, no custom UUIDs):
 *   0x180D  Heart Rate Service
 *   0x180F  Battery Service
 *   0x180A  Device Information Service
 * ============================================================= */

/* NOTE on byte order: the _BYTES form must be pure little-endian, i.e.
 * `value[0]` is the LSB of the UUID. NimBLE's `ble_uuid128_t.value` and
 * ESP-IDF's `esp_bt_uuid_t.uuid.uuid128` both use this layout, and it is
 * what gets emitted on the wire as-is. Earlier revisions of this header
 * mistakenly used Microsoft GUID layout (first 3 fields little-endian,
 * last 2 fields big-endian). That caused the firmware to advertise and
 * register service UUIDs that did NOT match the strings, which in turn
 * caused dashboard's getPrimaryService() to fail with NotFoundError. To
 * sanity-check a new entry: take the _STR form, strip dashes, pair into
 * bytes (big-endian display order), then reverse the entire 16-byte
 * sequence to get _BYTES. */

/* Custom Narbis service (primary) */
#define NARBIS_SVC_UUID_STR    "a24080b2-8857-4785-b3ba-a43b66af4f28"
#define NARBIS_SVC_UUID_BYTES  { 0x28, 0x4F, 0xAF, 0x66, 0x3B, 0xA4, 0xBA, 0xB3, 0x85, 0x47, 0x57, 0x88, 0xB2, 0x80, 0x40, 0xA2 }

/* IBI notify (per-beat or batched, depending on ble_profile) */
#define NARBIS_CHR_IBI_UUID_STR    "78ef492f-66be-438d-a91e-ddfdb441b7bb"
#define NARBIS_CHR_IBI_UUID_BYTES  { 0xBB, 0xB7, 0x41, 0xB4, 0xFD, 0xDD, 0x1E, 0xA9, 0x8D, 0x43, 0xBE, 0x66, 0x2F, 0x49, 0xEF, 0x78 }

/* SQI notify (signal quality indicator) */
#define NARBIS_CHR_SQI_UUID_STR    "2b614c61-bcdf-4a3f-a7e8-3b5a860c0347"
#define NARBIS_CHR_SQI_UUID_BYTES  { 0x47, 0x03, 0x0C, 0x86, 0x5A, 0x3B, 0xE8, 0xA7, 0x3F, 0x4A, 0xDF, 0xBC, 0x61, 0x4C, 0x61, 0x2B }

/* Raw PPG notify (gated on data_format) */
#define NARBIS_CHR_RAW_PPG_UUID_STR    "6bacca91-7017-40fa-bb91-4ebf28a65a99"
#define NARBIS_CHR_RAW_PPG_UUID_BYTES  { 0x99, 0x5A, 0xA6, 0x28, 0xBF, 0x4E, 0x91, 0xBB, 0xFA, 0x40, 0x17, 0x70, 0x91, 0xCA, 0xAC, 0x6B }

/* Custom battery notify (richer than standard 0x180F) */
#define NARBIS_CHR_BATTERY_UUID_STR    "b59d3ba1-78d1-4260-93c2-7e9e02329777"
#define NARBIS_CHR_BATTERY_UUID_BYTES  { 0x77, 0x97, 0x32, 0x02, 0x9E, 0x7E, 0xC2, 0x93, 0x60, 0x42, 0xD1, 0x78, 0xA1, 0x3B, 0x9D, 0xB5 }

/* Current runtime config — read + notify */
#define NARBIS_CHR_CONFIG_UUID_STR    "553abc98-6406-4e37-b9fd-34df85b2b6c1"
#define NARBIS_CHR_CONFIG_UUID_BYTES  { 0xC1, 0xB6, 0xB2, 0x85, 0xDF, 0x34, 0xFD, 0xB9, 0x37, 0x4E, 0x06, 0x64, 0x98, 0xBC, 0x3A, 0x55 }

/* Config write (whole struct or single field) */
#define NARBIS_CHR_CONFIG_WRITE_UUID_STR    "129fbe56-cbd6-4f52-957b-d80834d6abf3"
#define NARBIS_CHR_CONFIG_WRITE_UUID_BYTES  { 0xF3, 0xAB, 0xD6, 0x34, 0x08, 0xD8, 0x7B, 0x95, 0x52, 0x4F, 0xD6, 0xCB, 0x56, 0xBE, 0x9F, 0x12 }

/* Mode write (2-axis: ble_profile / data_format).
 * Wire layout is unchanged from the 3-axis version: mode_byte still packs
 * transport(2) | ble_profile(2) | data_format(2) | reserved(2). transport
 * field is now ignored on read and written as 0; kept for byte-layout
 * compat with older NVS blobs that survived a pre-config_version-3 boot. */
#define NARBIS_CHR_MODE_UUID_STR    "71db6de8-5bff-480f-8db1-0d01c90d17d0"
#define NARBIS_CHR_MODE_UUID_BYTES  { 0xD0, 0x17, 0x0D, 0xC9, 0x01, 0x0D, 0xB1, 0x8D, 0x0F, 0x48, 0xFF, 0x5B, 0xE8, 0x6D, 0xDB, 0x71 }

/* Peer-role write — central tells earclip what kind of peer it is.
 * 1 byte: 0=unknown, 1=dashboard, 2=glasses. Earclip applies the right
 * BLE conn-update profile per role (DASHBOARD→LOW_LATENCY, GLASSES→
 * BATCHED). Not persisted; central re-announces on every connect. */
#define NARBIS_CHR_PEER_ROLE_UUID_STR    "e987719a-26a6-48d4-b8e9-128994e62e6c"
#define NARBIS_CHR_PEER_ROLE_UUID_BYTES  { 0x6C, 0x2E, 0xE6, 0x94, 0x89, 0x12, 0xE9, 0xB8, 0xD4, 0x48, 0xA6, 0x26, 0x9A, 0x71, 0x87, 0xE9 }

/* OTA service — Edge-compatible 16-bit UUIDs (ported from existing Edge
 * firmware so a single OTA webapp updates both products). Three
 * characteristics: control point (write+read), data packets (write WoR),
 * status notifications. Page-based CRC32 transfer, not standard Nordic
 * Secure DFU — see `staged-prompts/08_firmware_ota.md`. */
#define NARBIS_OTA_SVC_UUID16          0x00FFu
#define NARBIS_OTA_CHR_CONTROL_UUID16  0xFF01u
#define NARBIS_OTA_CHR_DATA_UUID16     0xFF02u
#define NARBIS_OTA_CHR_STATUS_UUID16   0xFF03u

/* Diagnostics notify (free heap, uptime, RSSI, etc.) */
#define NARBIS_CHR_DIAGNOSTICS_UUID_STR    "31d99572-bf8a-4658-828e-4f7c138ca722"
#define NARBIS_CHR_DIAGNOSTICS_UUID_BYTES  { 0x22, 0xA7, 0x8C, 0x13, 0x7C, 0x4F, 0x8E, 0x82, 0x58, 0x46, 0x8A, 0xBF, 0x72, 0x95, 0xD9, 0x31 }

/* =============================================================
 * Enums
 * ============================================================= */

/* Legacy ESP-NOW message types. Path B (config_version 3) removed the
 * ESP-NOW transport entirely; these values survive only because the BLE
 * GATT-side per-stream payload structs reference them via the in-memory
 * narbis_packet_t union helpers. After full cleanup, this enum and the
 * packet machinery below can be deleted. Values are stable on the wire —
 * never renumber. */
typedef enum {
    NARBIS_MSG_IBI            = 0x01,
    NARBIS_MSG_RAW_PPG        = 0x02,
    NARBIS_MSG_BATTERY        = 0x03,
    NARBIS_MSG_SQI            = 0x04,
    NARBIS_MSG_HEARTBEAT      = 0x05,
    NARBIS_MSG_CONFIG_ACK     = 0x06
} narbis_msg_type_t;

/* Peer role — central announces its role to the earclip via a 1-byte
 * write to NARBIS_CHR_PEER_ROLE on each connect. Earclip uses this to
 * pick the per-connection BLE conn-update profile. */
typedef enum {
    NARBIS_PEER_ROLE_UNKNOWN   = 0,
    NARBIS_PEER_ROLE_DASHBOARD = 1,
    NARBIS_PEER_ROLE_GLASSES   = 2
} narbis_peer_role_t;

/* BLE profile — controls notify cadence. */
typedef enum {
    NARBIS_BLE_BATCHED     = 0,  /* one notify every ble_batch_period_ms */
    NARBIS_BLE_LOW_LATENCY = 1   /* notify every beat */
} narbis_ble_profile_t;

/* Data format — what the dashboard wants to see. */
typedef enum {
    NARBIS_DATA_IBI_ONLY     = 0,
    NARBIS_DATA_RAW_PPG      = 1,
    NARBIS_DATA_IBI_PLUS_RAW = 2
} narbis_data_format_t;

/* Detector mode (config_version 4). FIXED keeps the proven Elgendi rule-based
 * detector unchanged. ADAPTIVE wraps it with online template matching (NCC),
 * a 1-D Kalman filter on IBI, self-tuning alpha, and a state watchdog. The
 * adaptive path adds template_window_ms/2 of look-ahead — at the default
 * 200 Hz sample rate that's 100 ms, well inside the <300 ms target. */
typedef enum {
    NARBIS_DETECTOR_FIXED    = 0,
    NARBIS_DETECTOR_ADAPTIVE = 1
} narbis_detector_mode_t;

/* Beat-event flag bitmask (union of zero or more bits). */
#define NARBIS_BEAT_FLAG_ARTIFACT       0x01u
#define NARBIS_BEAT_FLAG_LOW_SQI        0x02u
#define NARBIS_BEAT_FLAG_INTERPOLATED   0x04u
#define NARBIS_BEAT_FLAG_LOW_CONFIDENCE 0x08u

/* CONFIG_ACK status codes. */
typedef enum {
    NARBIS_CFG_ACK_OK               = 0,
    NARBIS_CFG_ACK_RANGE_ERROR      = 1,
    NARBIS_CFG_ACK_UNKNOWN_FIELD    = 2,
    NARBIS_CFG_ACK_REQUIRES_REBOOT  = 3
} narbis_config_ack_status_t;

/* OTA control-point opcodes (byte 0 of a 2-byte write to NARBIS_OTA_CHR_CONTROL).
 * Values match the Edge firmware byte-for-byte. */
typedef enum {
    NARBIS_OTA_OP_START         = 0xA8,  /* param=0x00; enter OTA mode */
    NARBIS_OTA_OP_FINISH        = 0xA9,  /* param=0x00; flush, set boot, reboot */
    NARBIS_OTA_OP_CANCEL        = 0xAA,  /* param=0x00; abort transfer */
    NARBIS_OTA_OP_PAGE_CONFIRM  = 0xAD   /* param=0x01 commit / 0x00 resend */
} narbis_ota_opcode_t;

/* OTA status notification codes (byte 0 of a notify on NARBIS_OTA_CHR_STATUS). */
typedef enum {
    NARBIS_OTA_ST_READY         = 0x01,  /* 4 bytes: 01 00 00 00 */
    NARBIS_OTA_ST_PROGRESS      = 0x02,  /* reserved (Edge defines, does not emit) */
    NARBIS_OTA_ST_SUCCESS       = 0x03,  /* 4 bytes: 03 00 00 00; reboot pending */
    NARBIS_OTA_ST_ERROR         = 0x04,  /* 4 bytes: 04 <err> 00 00 */
    NARBIS_OTA_ST_CANCELLED     = 0x05,  /* 4 bytes: 05 00 00 00 */
    NARBIS_OTA_ST_PAGE_CRC      = 0x06,  /* 7 bytes: 06 page_hi page_lo crc32_le[4] */
    NARBIS_OTA_ST_PAGE_OK       = 0x07,  /* 3 bytes: 07 page_hi page_lo */
    NARBIS_OTA_ST_PAGE_RESEND   = 0x08   /* 3 bytes: 08 page_hi page_lo */
} narbis_ota_status_t;

/* OTA error codes (byte 1 of NARBIS_OTA_ST_ERROR notification).
 * Codes 0x01–0x05 match Edge. 0x06–0x08 are earclip additions for the
 * battery / chip-id / re-entry safety layers. */
typedef enum {
    NARBIS_OTA_ERR_BEGIN        = 0x01,  /* esp_ota_begin failed */
    NARBIS_OTA_ERR_WRITE        = 0x02,  /* esp_ota_write failed */
    NARBIS_OTA_ERR_END          = 0x03,  /* esp_ota_end / set_boot failed */
    NARBIS_OTA_ERR_NOT_IN_OTA   = 0x04,  /* data received outside OTA session */
    NARBIS_OTA_ERR_NO_PARTITION = 0x05,  /* esp_ota_get_next_update_partition NULL */
    NARBIS_OTA_ERR_LOW_BATTERY  = 0x06,  /* SoC < 30% (earclip addition) */
    NARBIS_OTA_ERR_CHIP_MISMATCH= 0x07,  /* image not for ESP32-C6 (earclip addition) */
    NARBIS_OTA_ERR_ALREADY_IN_OTA = 0x08 /* START received while already in OTA (earclip addition) */
} narbis_ota_error_t;

/* OTA wire constants — must match Edge. */
#define NARBIS_OTA_PAGE_SIZE   4096u
#define NARBIS_OTA_CHUNK_SIZE   244u    /* informational: BLE-MTU-safe */

/* =============================================================
 * Per-message payload structs (wire format)
 *
 * On the wire, only the active variant's bytes are emitted, preceded
 * by the packet header and followed by a 16-bit CRC. Payload size is
 * carried in the header's payload_len field.
 * ============================================================= */

/* Maximum samples per RAW_PPG packet, chosen so the full ESP-NOW frame
 * (header 12 + payload + crc 2) stays within the 250-byte ESP-NOW limit:
 *   header(12) + raw_ppg_header(4) + 29 * sample(8) + crc(2) = 250
 */
#define NARBIS_RAW_PPG_MAX_SAMPLES 29

/* IBI payload — a single inter-beat interval observation. */
typedef struct __attribute__((packed)) {
    uint16_t ibi_ms;            /* inter-beat interval, milliseconds (300–2000 typ.) */
    uint8_t  confidence_x100;   /* 0–100 → 0.00–1.00 confidence */
    uint8_t  flags;             /* NARBIS_BEAT_FLAG_* bitmask */
} narbis_ibi_payload_t;

/* RAW_PPG sample — one (red, IR) pair from the MAX3010x FIFO. */
typedef struct __attribute__((packed)) {
    uint32_t red;               /* raw ADC counts, channel red */
    uint32_t ir;                /* raw ADC counts, channel IR */
} narbis_raw_sample_t;

/* RAW_PPG payload — variable-length sample batch. n_samples ≤ NARBIS_RAW_PPG_MAX_SAMPLES. */
typedef struct __attribute__((packed)) {
    uint16_t sample_rate_hz;    /* sample rate at time of capture (Hz) */
    uint16_t n_samples;         /* number of valid entries in samples[] */
    narbis_raw_sample_t samples[NARBIS_RAW_PPG_MAX_SAMPLES];
} narbis_raw_ppg_payload_t;

/* BATTERY payload. */
typedef struct __attribute__((packed)) {
    uint16_t mv;                /* battery voltage in millivolts */
    uint8_t  soc_pct;           /* state of charge, 0–100 */
    uint8_t  charging;          /* 0 = not charging, 1 = charging */
} narbis_battery_payload_t;

/* SQI payload — signal quality indicator. */
typedef struct __attribute__((packed)) {
    uint16_t sqi_x100;             /* 0–100 → 0.00–1.00 signal quality */
    uint32_t dc_red;               /* DC level, red channel (ADC counts) */
    uint32_t dc_ir;                /* DC level, IR channel (ADC counts) */
    uint16_t perfusion_idx_x1000;  /* perfusion index × 1000 */
} narbis_sqi_payload_t;

/* HEARTBEAT payload — keepalive plus a small diagnostics digest.
 *
 * mode_byte packs the three mode enums for compactness:
 *   bits 0–1: transport_mode
 *   bits 2–3: ble_profile
 *   bits 4–5: data_format
 *   bits 6–7: reserved (must be 0)
 */
typedef struct __attribute__((packed)) {
    uint32_t uptime_s;          /* seconds since boot */
    uint32_t free_heap;         /* bytes of free heap on the earclip */
    int8_t   rssi_dbm;          /* last-seen ESP-NOW RSSI to peer */
    uint8_t  mode_byte;         /* packed mode enums (see above) */
    uint16_t reserved;          /* must be 0 */
} narbis_heartbeat_payload_t;

/* CONFIG_ACK payload — response to a config write. */
typedef struct __attribute__((packed)) {
    uint16_t config_version;    /* echo of config_version after write */
    uint8_t  status;            /* narbis_config_ack_status_t */
    uint8_t  field_id;          /* offset (in bytes) of the field, or 0xFF for whole-struct */
} narbis_config_ack_payload_t;

/* =============================================================
 * Packet header + in-memory packet
 *
 * Wire layout (variable length):
 *   [header 12 B][active payload (payload_len bytes)][crc16 2 B]
 *
 * The in-memory narbis_packet_t stores the full payload union for
 * ergonomic access; serialize/deserialize emit/consume only the active
 * variant's bytes based on header.msg_type.
 * ============================================================= */

typedef struct __attribute__((packed)) {
    uint8_t  msg_type;          /* narbis_msg_type_t */
    uint8_t  device_id;         /* per-earclip ID (0 = unset) */
    uint16_t seq_num;           /* per-(device,msg_type) monotonic counter */
    uint32_t timestamp_ms;      /* earclip-local milliseconds */
    uint16_t payload_len;       /* bytes of payload following this header */
    uint8_t  protocol_version;  /* must equal NARBIS_PROTOCOL_VERSION */
    uint8_t  reserved;          /* must be 0 */
} narbis_header_t;

#define NARBIS_HEADER_SIZE 12u
#define NARBIS_CRC_SIZE     2u
#define NARBIS_FRAME_OVERHEAD (NARBIS_HEADER_SIZE + NARBIS_CRC_SIZE)
#define NARBIS_MAX_FRAME_SIZE 250u  /* ESP-NOW payload cap */
#define NARBIS_MAX_PAYLOAD_SIZE (NARBIS_MAX_FRAME_SIZE - NARBIS_FRAME_OVERHEAD)

typedef union {
    narbis_ibi_payload_t           ibi;
    narbis_raw_ppg_payload_t       raw_ppg;
    narbis_battery_payload_t       battery;
    narbis_sqi_payload_t           sqi;
    narbis_heartbeat_payload_t     heartbeat;
    narbis_config_ack_payload_t    config_ack;
} narbis_payload_t;

typedef struct {
    narbis_header_t  header;
    narbis_payload_t payload;
    uint16_t         crc16;     /* populated by serialize / verified by deserialize */
} narbis_packet_t;

/* =============================================================
 * Internal: beat_event_t
 *
 * Emitted by beat_validator, consumed by transport tasks. Carries more
 * context than the on-wire IBI payload (e.g. peak amplitude, sample
 * index for cross-referencing raw PPG). NEVER serialized to the wire.
 * ============================================================= */

typedef struct {
    uint32_t timestamp_ms;      /* earclip-local time at peak */
    uint16_t ibi_ms;            /* time since previous valid beat */
    uint16_t prev_ibi_ms;       /* IBI of the beat before this one (continuity check) */
    uint8_t  confidence_x100;   /* 0–100 */
    uint8_t  flags;             /* NARBIS_BEAT_FLAG_* */
    uint16_t peak_amplitude;    /* filtered-signal amplitude at the peak */
    uint32_t sample_index;      /* sample number from start of session */
} beat_event_t;

/* =============================================================
 * Runtime config
 *
 * Persisted to NVS, write-able via NARBIS_CHR_CONFIG_WRITE. Every field
 * is dashboard-tweakable. With the exception of sample_rate_hz, all
 * fields apply at runtime without a reboot.
 * ============================================================= */

typedef struct __attribute__((packed)) {
    /* ---- meta ----
     * config_version: increments on incompatible NVS changes.
     *   1 — initial.
     *   2 — diagnostics_mask repurposed from reserved_pwr.
     *   3 — Path B: removed transport_mode / partner_mac / espnow_channel
     *       (ESP-NOW deleted). Older blobs harmlessly fall back to defaults
     *       on load via the version>=3 check in config_manager_init.
     *   4 — Path C: added detector_mode + adaptive-detector params
     *       (NCC template, Kalman, watchdog) and Layer-E auxiliary
     *       knobs (agc_adaptive_step, refractory_ibi_pct). Older blobs
     *       are rejected and defaults are loaded; the new fields zero
     *       to FIXED-mode behavior so a partial blob would still be safe. */
    uint16_t config_version;

    /* ---- sensor ---- */
    uint16_t sample_rate_hz;        /* 50 / 100 / 200 / 400; reboot to apply */
    uint16_t led_red_ma_x10;        /* red LED current ×10 (default 70 = 7.0 mA) */
    uint16_t led_ir_ma_x10;         /* IR  LED current ×10 (default 70 = 7.0 mA) */

    /* ---- AGC ---- */
    uint8_t  agc_enabled;           /* 0/1 */
    uint8_t  reserved_agc;          /* pad to 16-bit boundary */
    uint16_t agc_update_period_ms;  /* how often AGC re-evaluates (default 200) */
    uint32_t agc_target_dc_min;     /* lower DC target (ADC counts) */
    uint32_t agc_target_dc_max;     /* upper DC target (ADC counts) */
    uint16_t agc_step_ma_x10;       /* per-update LED current step ×10 */

    /* ---- DSP ---- */
    uint16_t bandpass_low_hz_x100;  /* bandpass low cutoff ×100 (default 50 = 0.50 Hz) */
    uint16_t bandpass_high_hz_x100; /* bandpass high cutoff ×100 (default 800 = 8.00 Hz) */
    uint16_t elgendi_w1_ms;         /* Elgendi systolic peak window (ms, default 111) */
    uint16_t elgendi_w2_ms;         /* Elgendi beat window (ms, default 667) */
    uint16_t elgendi_beta_x1000;    /* Elgendi offset coefficient ×1000 (default 20 = 0.020) */

    /* ---- beat validator / SQI gating ---- */
    uint16_t sqi_threshold_x100;    /* min SQI to emit IBI (default 50 = 0.50) */
    uint16_t ibi_min_ms;            /* validator floor (default 300, ≈200 BPM)
                                     * also used as Elgendi refractory period */
    uint16_t ibi_max_ms;            /* validator ceiling (default 2000, ≈30 BPM) */
    uint8_t  ibi_max_delta_pct;     /* continuity threshold (default 30) */

    /* ---- mode (2-axis after Path B) ---- */
    uint8_t  ble_profile;           /* narbis_ble_profile_t */
    uint8_t  data_format;           /* narbis_data_format_t */

    /* ---- transport ---- */
    uint16_t ble_batch_period_ms;   /* BATCHED mode flush interval (default 500) */

    /* ---- power / diag ---- */
    uint8_t  diagnostics_enabled;   /* 0/1 — master enable for diagnostics emission */
    uint8_t  light_sleep_enabled;   /* 0/1 */
    uint8_t  diagnostics_mask;      /* NARBIS_DIAG_STREAM_* bitmask; 0 = none. Repurposed
                                     * from reserved_pwr in config_version 2. */
    uint16_t battery_low_mv;        /* below this, signal low-battery (default 3300) */

    /* ---- adaptive detector (config_version 4) ----
     * Set detector_mode=NARBIS_DETECTOR_FIXED to revert to the proven rule-based
     * Elgendi pipeline. All other fields below are ignored when FIXED. */
    uint8_t  detector_mode;              /* narbis_detector_mode_t (default FIXED) */
    uint8_t  template_max_beats;         /* rolling template depth (default 10) */
    uint8_t  template_warmup_beats;      /* beats before NCC gate activates (default 4) */
    uint8_t  kalman_warmup_beats;        /* beats before Kalman gate activates (default 5) */
    uint16_t template_window_ms;         /* matched-filter window length, ms (default 200) */
    uint16_t ncc_min_x1000;              /* admit threshold, NCC ×1000 (default 500 = 0.500) */
    uint16_t ncc_learn_min_x1000;        /* template-learning threshold (default 750 = 0.750) */
    uint16_t kalman_q_ms2;               /* process noise variance, ms² (default 400) */
    uint16_t kalman_r_ms2;               /* measurement noise baseline, ms² (default 2500) */
    uint8_t  kalman_sigma_x10;           /* IBI gate width, σ ×10 (default 30 = 3.0σ) */
    uint8_t  watchdog_max_consec_rejects;/* full-reset trigger (default 5) */
    uint16_t watchdog_silence_ms;        /* full-reset silence trigger, ms (default 4000) */
    uint16_t alpha_min_x1000;            /* α floor ×1000 (default 10 = 0.010) */
    uint16_t alpha_max_x1000;            /* α ceiling ×1000 (default 500 = 0.500) */

    /* ---- adaptive auxiliary (Layer E, Tier 1) ---- */
    uint8_t  elgendi_loose_mode;         /* 0/1 — relax Elgendi β and NCC admit by 50% for
                                          * motion tolerance. Repurposed from former
                                          * agc_adaptive_step (same wire byte, same range). */
    uint8_t  refractory_ibi_pct;         /* refractory = ibi_min_ms .. (pct/100)·IBI (default 60) */
} narbis_runtime_config_t;

/* =============================================================
 * Edge glasses coherence-pipeline tuning struct.
 *
 * Lives on the Edge glasses (not the earclip). Written via CTRL opcode
 * 0xE0 on the glasses' 0xFF01 characteristic; the dashboard exposes the
 * fields as sliders. Lets the user re-tune the LF peak window, band
 * boundaries, IBI gating, and coherence scaling at runtime without a
 * reflash — keeps Approach A's "one source of truth" guarantee while
 * removing the "coordinated firmware+dashboard updates" cost when
 * iterating on the algorithm.
 *
 * Bin units are FFT-bin indices at the firmware's fixed 4 Hz × 256-point
 * grid (df = 0.015625 Hz/bin). Compile-time grid is NOT runtime-tunable;
 * resizing the static FFT buffers would mean dynamic allocation.
 *
 * NOTE: the on-glasses NVS storage is one u8 per field (see prefs_load
 * in EDGE firmware main.c) for simplicity; the wire format below is the
 * struct as-is.
 * ============================================================= */
typedef struct __attribute__((packed)) {
    uint8_t  min_ibis;             /* default 20; minimum beats to compute coherence */
    uint8_t  conf_threshold;       /* default 50; drop IBIs with conf<this in on_earclip_ibi / 0xCA */
    /* Band-integration bin ranges (inclusive) */
    uint8_t  vlf_band_lo;          /* default 1  */
    uint8_t  vlf_band_hi;          /* default 2  */
    uint8_t  lf_band_lo;           /* default 3  */
    uint8_t  lf_band_hi;           /* default 9  */
    uint8_t  hf_band_lo;           /* default 10 */
    uint8_t  hf_band_hi;           /* default 25 */
    /* LF-peak search (Lehrer/Vaschillo numerator) */
    uint8_t  lf_peak_lo;           /* default 3  */
    uint8_t  lf_peak_hi;           /* default 9  */
    uint8_t  peak_halfwidth;       /* default 0 → single-bin peak; N → ±N bins inclusive */
    /* Score scaling */
    uint8_t  coh_multiplier;       /* default 100 (was 250 pre-v4.14.31) */
} narbis_coh_params_t;

#define NARBIS_COH_PARAMS_WIRE_SIZE 12u  /* matches sizeof(narbis_coh_params_t) */

#define NARBIS_COH_PARAMS_DEFAULTS_INIT { \
    .min_ibis        = 20,  \
    .conf_threshold  = 50,  \
    .vlf_band_lo     = 1,   \
    .vlf_band_hi     = 2,   \
    .lf_band_lo      = 3,   \
    .lf_band_hi      = 9,   \
    .hf_band_lo      = 10,  \
    .hf_band_hi      = 25,  \
    .lf_peak_lo      = 3,   \
    .lf_peak_hi      = 9,   \
    .peak_halfwidth  = 0,   \
    .coh_multiplier  = 100, \
}

/* Diagnostics stream IDs — bit positions in narbis_runtime_config_t.diagnostics_mask.
 * Each stream is independently subscribable; emission also requires the
 * master diagnostics_enabled flag to be 1 and a NARBIS_CHR_DIAGNOSTICS
 * subscriber. */
#define NARBIS_DIAG_STREAM_PRE_FILTER   (1u << 0)  /* raw DC-removed PPG samples */
#define NARBIS_DIAG_STREAM_POST_FILTER  (1u << 1)  /* bandpass-filtered samples */
#define NARBIS_DIAG_STREAM_PEAK_CAND    (1u << 2)  /* Elgendi peak candidates pre-validator */
#define NARBIS_DIAG_STREAM_AGC_EVENT    (1u << 3)  /* per-AGC-step LED current changes */
#define NARBIS_DIAG_STREAM_FIFO_OCCUP   (1u << 4)  /* MAX3010x FIFO occupancy at each drain */
#define NARBIS_DIAG_STREAM_DETECTOR_STATS (1u << 5) /* adaptive detector snapshot per beat */

/* =============================================================
 * Helper API (impl in narbis_protocol.c)
 * ============================================================= */

/* CRC-16-CCITT-FALSE: poly 0x1021, init 0xFFFF, no reflect, no xor-out. */
uint16_t narbis_crc16_ccitt_false(const uint8_t *data, size_t len);

/* Returns the wire payload size for the given message type and packet,
 * or 0 if msg_type is unknown. RAW_PPG depends on n_samples. */
size_t narbis_payload_size(const narbis_packet_t *pkt);

/* Serialize pkt into buf. *out_len is set to the total bytes written
 * (header + payload + crc). Returns 0 on success, negative on error
 * (buf too small / unknown msg_type / payload too large). */
int narbis_packet_serialize(uint8_t *buf, size_t buf_len,
                            const narbis_packet_t *pkt, size_t *out_len);

/* Deserialize buf into pkt. Verifies CRC, protocol_version, and that
 * payload_len matches msg_type. Returns 0 on success, negative on error. */
int narbis_packet_deserialize(const uint8_t *buf, size_t buf_len,
                              narbis_packet_t *pkt);

/* Serialize / deserialize the runtime config. The wire form is just the
 * packed struct bytes followed by a CRC-16. */
int narbis_config_serialize(uint8_t *buf, size_t buf_len,
                            const narbis_runtime_config_t *cfg, size_t *out_len);
int narbis_config_deserialize(const uint8_t *buf, size_t buf_len,
                              narbis_runtime_config_t *cfg);

#define NARBIS_CONFIG_WIRE_SIZE (sizeof(narbis_runtime_config_t) + NARBIS_CRC_SIZE)

#ifdef __cplusplus
}
#endif

#endif /* NARBIS_PROTOCOL_H */
